name: Guillaume St.Michel
favicon: null
layout_spectrum: 0.4047984117642045
typography_spectrum: 0.6688018932472914
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#444444'
    - '#dddddd'
    - '#ababab'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
